- Target: nmaguiar/imgutils:build-lite (alpine 3.21.0_alpha20240923)
  Class: os-pkgs
  Type: alpine
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45338
    PkgID: golang.org/x/net@v0.30.0
    PkgName: golang.org/x/net
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/net@v0.30.0
      UID: 9ce1984a5172bc7c
    InstalledVersion: v0.30.0
    FixedVersion: 0.33.0
    Status: fixed
    Layer:
      Digest: sha256:fd384cfc120440f29d63e71c8b3eb6702121b13974ad8b35547a495e34f4d533
      DiffID: sha256:f5e67e5c0a8c40381922bde0525b1b8218de62d9d904324c806daaaa0155c579
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45338
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'golang.org/x/net/html: Non-linear parsing of case-insensitive content in golang.org/x/net/html'
    Description: An attacker can craft an input to the Parse functions that would be processed non-linearly with respect to its length, resulting in extremely slow parsing. This could cause a denial of service.
    Severity: HIGH
    VendorSeverity:
      ghsa: 3
      redhat: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45338
    - https://cs.opensource.google/go/x/net
    - https://github.com/golang/go/issues/70906
    - https://go.dev/cl/637536
    - https://go.dev/issue/70906
    - https://groups.google.com/g/golang-announce/c/wSCRmFnNmPA/m/Lvcd0mRMAwAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45338
    - https://pkg.go.dev/vuln/GO-2024-3333
    - https://www.cve.org/CVERecord?id=CVE-2024-45338
    PublishedDate: '2024-12-18T21:15:08.173Z'
    LastModifiedDate: '2024-12-18T21:15:08.173Z'
