- Target: nmaguiar/imgutils:lite (alpine 3.20.2)
  Class: os-pkgs
  Type: alpine
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-34156
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34156
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'encoding/gob: golang: Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion'
    Description: Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion. This is a follow-up to CVE-2022-30635.
    Severity: HIGH
    VendorSeverity:
      alma: 3
      amazon: 3
      bitnami: 3
      oracle-oval: 3
      redhat: 3
      rocky: 3
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/errata/RHSA-2024:8112
    - https://access.redhat.com/security/cve/CVE-2024-34156
    - https://bugzilla.redhat.com/2310527
    - https://bugzilla.redhat.com/2310528
    - https://bugzilla.redhat.com/2310529
    - https://bugzilla.redhat.com/2315691
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310528
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34156
    - https://errata.almalinux.org/9/ALSA-2024-8112.html
    - https://errata.rockylinux.org/RLSA-2024:7204
    - https://go.dev/cl/611239
    - https://go.dev/issue/69139
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://linux.oracle.com/cve/CVE-2024-34156.html
    - https://linux.oracle.com/errata/ELSA-2024-8112.html
    - https://nvd.nist.gov/vuln/detail/CVE-2024-34156
    - https://pkg.go.dev/vuln/GO-2024-3106
    - https://www.cve.org/CVERecord?id=CVE-2024-34156
    PublishedDate: '2024-09-06T21:15:12.02Z'
    LastModifiedDate: '2024-09-09T15:35:07.573Z'
  - VulnerabilityID: CVE-2024-34155
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34155
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'go/parser: golang: Calling any of the Parse functions containing deeply nested literals can cause a panic/stack exhaustion'
    Description: Calling any of the Parse functions on Go source code which contains deeply nested literals can cause a panic due to stack exhaustion.
    Severity: MEDIUM
    VendorSeverity:
      alma: 3
      amazon: 3
      oracle-oval: 3
      redhat: 2
      rocky: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
    References:
    - https://access.redhat.com/errata/RHSA-2024:8112
    - https://access.redhat.com/security/cve/CVE-2024-34155
    - https://bugzilla.redhat.com/2310527
    - https://bugzilla.redhat.com/2310528
    - https://bugzilla.redhat.com/2310529
    - https://bugzilla.redhat.com/2315691
    - https://bugzilla.redhat.com/show_bug.cgi?id=2295310
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310527
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310528
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310529
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-24791
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34155
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34156
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34158
    - https://errata.almalinux.org/9/ALSA-2024-8112.html
    - https://errata.rockylinux.org/RLSA-2024:6913
    - https://go.dev/cl/611238
    - https://go.dev/issue/69138
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://linux.oracle.com/cve/CVE-2024-34155.html
    - https://linux.oracle.com/errata/ELSA-2024-8112.html
    - https://nvd.nist.gov/vuln/detail/CVE-2024-34155
    - https://pkg.go.dev/vuln/GO-2024-3105
    - https://www.cve.org/CVERecord?id=CVE-2024-34155
    PublishedDate: '2024-09-06T21:15:11.947Z'
    LastModifiedDate: '2024-09-09T13:03:38.303Z'
  - VulnerabilityID: CVE-2024-34158
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34158
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'go/build/constraint: golang: Calling Parse on a "// +build" build tag line with deeply nested expressions can cause a panic due to stack exhaustion'
    Description: Calling Parse on a "// +build" build tag line with deeply nested expressions can cause a panic due to stack exhaustion.
    Severity: MEDIUM
    CweIDs:
    - CWE-674
    VendorSeverity:
      alma: 3
      amazon: 3
      bitnami: 3
      oracle-oval: 3
      redhat: 2
      rocky: 3
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
    References:
    - https://access.redhat.com/errata/RHSA-2024:8112
    - https://access.redhat.com/security/cve/CVE-2024-34158
    - https://bugzilla.redhat.com/2310527
    - https://bugzilla.redhat.com/2310528
    - https://bugzilla.redhat.com/2310529
    - https://bugzilla.redhat.com/2315691
    - https://bugzilla.redhat.com/show_bug.cgi?id=2295310
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310527
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310528
    - https://bugzilla.redhat.com/show_bug.cgi?id=2310529
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-24791
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34155
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34156
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-34158
    - https://errata.almalinux.org/9/ALSA-2024-8112.html
    - https://errata.rockylinux.org/RLSA-2024:6913
    - https://go.dev/cl/611240
    - https://go.dev/issue/69141
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://linux.oracle.com/cve/CVE-2024-34158.html
    - https://linux.oracle.com/errata/ELSA-2024-8112.html
    - https://nvd.nist.gov/vuln/detail/CVE-2024-34158
    - https://pkg.go.dev/vuln/GO-2024-3107
    - https://www.cve.org/CVERecord?id=CVE-2024-34158
    PublishedDate: '2024-09-06T21:15:12.083Z'
    LastModifiedDate: '2024-09-09T14:35:01.17Z'
