- Target: nmaguiar/imgutils:build (alpine 3.20.3)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/ctr
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/dive
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/docker
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/helm
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/nerdctl
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/skopeo
  Class: lang-pkgs
  Type: gobinary
