- Target: nmaguiar/imgutils:lite (alpine 3.20.2)
  Class: os-pkgs
  Type: alpine
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-34155
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34155
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Description: Calling any of the Parse functions on Go source code which contains deeply nested literals can cause a panic due to stack exhaustion.
    Severity: UNKNOWN
    References:
    - https://go.dev/cl/611238
    - https://go.dev/issue/69138
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://pkg.go.dev/vuln/GO-2024-3105
    PublishedDate: '2024-09-06T21:15:11.947Z'
    LastModifiedDate: '2024-09-06T21:15:11.947Z'
  - VulnerabilityID: CVE-2024-34156
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34156
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Description: Calling Decoder.Decode on a message which contains deeply nested structures can cause a panic due to stack exhaustion. This is a follow-up to CVE-2022-30635.
    Severity: UNKNOWN
    References:
    - https://go.dev/cl/611239
    - https://go.dev/issue/69139
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://pkg.go.dev/vuln/GO-2024-3106
    PublishedDate: '2024-09-06T21:15:12.02Z'
    LastModifiedDate: '2024-09-06T21:15:12.02Z'
  - VulnerabilityID: CVE-2024-34158
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@1.22.5
      UID: 409aacc5453c55c9
    InstalledVersion: 1.22.5
    FixedVersion: 1.22.7, 1.23.1
    Status: fixed
    Layer:
      Digest: sha256:f3249438f16442c3431450d02c710709543a36373ee2c1d6e1967809e000422e
      DiffID: sha256:13d5188d2a0a0940164d4d95d93c933e67057e8992efe51cadfd2beee75b4224
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-34158
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Description: Calling Parse on a "// +build" build tag line with deeply nested expressions can cause a panic due to stack exhaustion.
    Severity: UNKNOWN
    References:
    - https://go.dev/cl/611240
    - https://go.dev/issue/69141
    - https://groups.google.com/g/golang-dev/c/S9POB9NCTdk
    - https://pkg.go.dev/vuln/GO-2024-3107
    PublishedDate: '2024-09-06T21:15:12.083Z'
    LastModifiedDate: '2024-09-06T21:15:12.083Z'
