- Target: nmaguiar/imgutils:build (alpine 3.20.3)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/ctr
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/dive
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/docker
  Class: lang-pkgs
  Type: gobinary
- Target: usr/bin/helm
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45337
    PkgID: golang.org/x/crypto@v0.27.0
    PkgName: golang.org/x/crypto
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/crypto@v0.27.0
      UID: 2c48ad94df90e1d1
    InstalledVersion: v0.27.0
    FixedVersion: 0.31.0
    Status: fixed
    Layer:
      Digest: sha256:bf62ba0cfcfc74cf1d393a6bf7605adc9662f7bddff2354a6082121e401f30dd
      DiffID: sha256:8426951c9ed81e484dc5c88d6dfd48f71f739bfec58be336d2cfccfb10f832f6
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45337
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: Applications and libraries which misuse the ServerConfig.PublicKeyCall ...
    Description: Applications and libraries which misuse the ServerConfig.PublicKeyCallback callback may be susceptible to an authorization bypass.
    Severity: HIGH
    VendorSeverity:
      ghsa: 3
    References:
    - http://www.openwall.com/lists/oss-security/2024/12/11/2
    - https://github.com/golang/crypto
    - https://github.com/golang/crypto/commit/b4f1988a35dee11ec3e05d6bf3e90b695fbd8909
    - https://go.dev/cl/635315
    - https://go.dev/issue/70779
    - https://groups.google.com/g/golang-announce/c/-nPEi39gI4Q/m/cGVPJCqdAQAJ
    - https://pkg.go.dev/vuln/GO-2024-3321
    PublishedDate: '2024-12-12T02:02:07.97Z'
    LastModifiedDate: '2024-12-12T02:15:24.673Z'
- Target: usr/bin/nerdctl
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45337
    PkgID: golang.org/x/crypto@v0.30.0
    PkgName: golang.org/x/crypto
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/crypto@v0.30.0
      UID: 3d337ee7702116d6
    InstalledVersion: v0.30.0
    FixedVersion: 0.31.0
    Status: fixed
    Layer:
      Digest: sha256:bf62ba0cfcfc74cf1d393a6bf7605adc9662f7bddff2354a6082121e401f30dd
      DiffID: sha256:8426951c9ed81e484dc5c88d6dfd48f71f739bfec58be336d2cfccfb10f832f6
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45337
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: Applications and libraries which misuse the ServerConfig.PublicKeyCall ...
    Description: Applications and libraries which misuse the ServerConfig.PublicKeyCallback callback may be susceptible to an authorization bypass.
    Severity: HIGH
    VendorSeverity:
      ghsa: 3
    References:
    - http://www.openwall.com/lists/oss-security/2024/12/11/2
    - https://github.com/golang/crypto
    - https://github.com/golang/crypto/commit/b4f1988a35dee11ec3e05d6bf3e90b695fbd8909
    - https://go.dev/cl/635315
    - https://go.dev/issue/70779
    - https://groups.google.com/g/golang-announce/c/-nPEi39gI4Q/m/cGVPJCqdAQAJ
    - https://pkg.go.dev/vuln/GO-2024-3321
    PublishedDate: '2024-12-12T02:02:07.97Z'
    LastModifiedDate: '2024-12-12T02:15:24.673Z'
- Target: usr/bin/skopeo
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45337
    PkgID: golang.org/x/crypto@v0.29.0
    PkgName: golang.org/x/crypto
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/crypto@v0.29.0
      UID: aea5ecac33e8922e
    InstalledVersion: v0.29.0
    FixedVersion: 0.31.0
    Status: fixed
    Layer:
      Digest: sha256:bf62ba0cfcfc74cf1d393a6bf7605adc9662f7bddff2354a6082121e401f30dd
      DiffID: sha256:8426951c9ed81e484dc5c88d6dfd48f71f739bfec58be336d2cfccfb10f832f6
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45337
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: Applications and libraries which misuse the ServerConfig.PublicKeyCall ...
    Description: Applications and libraries which misuse the ServerConfig.PublicKeyCallback callback may be susceptible to an authorization bypass.
    Severity: HIGH
    VendorSeverity:
      ghsa: 3
    References:
    - http://www.openwall.com/lists/oss-security/2024/12/11/2
    - https://github.com/golang/crypto
    - https://github.com/golang/crypto/commit/b4f1988a35dee11ec3e05d6bf3e90b695fbd8909
    - https://go.dev/cl/635315
    - https://go.dev/issue/70779
    - https://groups.google.com/g/golang-announce/c/-nPEi39gI4Q/m/cGVPJCqdAQAJ
    - https://pkg.go.dev/vuln/GO-2024-3321
    PublishedDate: '2024-12-12T02:02:07.97Z'
    LastModifiedDate: '2024-12-12T02:15:24.673Z'
