ojob.io/sec/genSecBadge: ''
image: nmaguiar/imgutils:lite
file: .github/sec-lite.svg
reportFile: .github/sec-lite.yaml
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
