name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache dive
      uses: actions/cache@v4
      with:
        key : dive-${{ runner.arch }}
        path: |
          dive

    - name: list dive
      run : |
        find .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: nmaguiar/imgutils:build

    # - uses: docker/build-push-action@v3
    #   name: Build and push ubi
    #   with:
    #     platforms: linux/amd64,linux/arm64
    #     file: Dockerfile.ubi
    #     push: true
    #     tags: nmaguiar/imgutils:ubi-build
