name: Test images

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  test-syft:
    name   : test syft
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test syft
      uses: ./
      with:
        cmd: syft scan nmaguiar/imgutils -o cyclonedx-json
