name: Test

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Test
    steps      :
    - uses: actions/checkout@v4
      name: Checkout
